help/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from core import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='home'),

    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout_then_login, name='logout'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^profile/update/$', views.update_profile, name='profile-update'),
    url(r'^profile/change-password/$', views.change_password, name='profile-change-password'),
    url(r'^signup/$', views.signup, name='signup'),

    url(r'^announcement/$', views.announcement_list, name='announcement-list'),
    url(r'^announcement/create/$', views.announcement_create, name='announcement-create'),
    url(r'^announcement/(?P<pk>\d+)/$', views.announcement_detail, name='announcement-detail'),
    url(r'^announcement/(?P<pk>\d+)/update/$', views.announcement_update, name='announcement-update'),
    url(r'^announcement/(?P<pk>\d+)/delete/$', views.announcement_delete, name='announcement-delete'),

    url(r'^soldier/$', views.soldier_list, name='soldier-list'),
    url(r'^soldier/create/$', views.soldier_create, name='soldier-create'),
    url(r'^soldier/(?P<pk>\d+)/$', views.soldier_detail, name='soldier-detail'),
    url(r'^soldier/(?P<pk>\d+)/enroll/$', views.soldier_enroll_user, name='soldier-enroll-user'),
    url(r'^soldier/(?P<pk>\d+)/update/$', views.soldier_update, name='soldier-update'),

    url(r'^counsel/$', views.counsel, name='counsel'),
    url(r'^counsel/(?P<pk>\d+)/$', views.counsel_list, name='counsel-list'),
    url(r'^counsel/(?P<pk>\d+)/create/$', views.counsel_create, name='counsel-create'),
    url(r'^counsel/(?P<pk>\d+)/(?P<pkc>\d+)/$', views.counsel_detail, name='counsel-detail'),
    url(r'^counsel/(?P<pk>\d+)/create/popup/$', views.counsel_create_popup, name='counsel-create-popup'),

    url(r'^approval/$', views.approval, name='approval'),
    url(r'^approval/(?P<pk>\d+)/approve/$', views.approval_detail_approve, name='approval-detail-approve'),
    url(r'^approval/(?P<pk>\d+)/$', views.approval_detail_non_approve, name='approval-detail-non-approve'),
    url(r'^approval/(?P<pk>\d+)/status/$', views.approval_status, name='approval-status'),
    url(r'^approval/requestlist/$', views.approval_req_list, name='approval_req_list'),
    url(r'^approval/completedlist/$', views.approval_completed_list, name='approval_completed_list'),
    url(r'^approval/proceedlist/$', views.approval_proceed_list, name='approval_proceed_list'),
    url(r'^approval/(?P<pk>\d+)/approved-list', views.approval_last_approved, name='approval-last-approved'),

    url(r'^ajax/counsel_find_user/(?P<pk>\d+)/$', views.ajax_counsel, name='find-userlist'),
    url(r'^ajax/soldier_find_user/(?P<pk>\d+)/$', views.ajax_soldier, name='user-search'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.

class TimeStampedModel(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Profile(TimeStampedModel):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=20)
    department = models.CharField(max_length=100)
    position = models.CharField(max_length=20, null=True)
    phone_num = models.CharField(max_length=20)

    CHOICES = (
        (1,'대장'), (2,'중장'), (3,'소장'), (4,'준장'), (5,'대령'), (6,'중령'),
        (7,'소령'), (8,'대위'), (9,'중위'), (10,'소위'), (11,'준위'), (12,'원사'),
        (13,'상사'), (14,'중사'), (15,'하사'), (16,'병장'), (17,'상병'),
        (18,'일병'), (19,'이병'),
    )

    rank = models.IntegerField(choices = CHOICES, null=True)

    def __unicode__(self):
        return self.name

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

class Soldier(TimeStampedModel):
    superuser = models.ForeignKey(User)
    name = models.CharField(max_length=20)
    department = models.CharField(max_length=100)
    nth = models.IntegerField()
    image = models.ImageField(upload_to='image/', blank=True)
    phone_num = models.CharField(max_length=10)

    def __unicode__(self):
        return self.name


class SoldierDetail(TimeStampedModel):
    soldier = models.OneToOneField(Soldier, on_delete=models.CASCADE)
    family_info = models.TextField()
    education = models.TextField()
    birth = models.DateField()
    service_num = models.CharField(max_length=12)
    major = models.CharField(max_length=15)
    last_desease = models.TextField()
    first_counsel = models.TextField()
    plan = models.TextField()
    emergency_contact = models.CharField(max_length=20)


class Sol_User_rel(TimeStampedModel):
    soldier = models.ForeignKey(Soldier)
    user = models.ForeignKey(User)

    class Meta:
        unique_together = ('soldier', 'user',)

    def __unicode__(self):
        return self.soldier.name


class Announcement(TimeStampedModel):
    user = models.ForeignKey(User)
    importance = models.BooleanField(default=False)
    title = models.CharField(max_length=20)
    contents = models.TextField()
    attached = models.FileField(upload_to='documents/', blank=True)

    def __unicode__(self):
        return self.title


class Counsel(TimeStampedModel):
    user = models.ForeignKey(User)
    soldier = models.ForeignKey(Soldier, on_delete=models.CASCADE)
    date = models.DateField()
    contents = models.TextField()
    plan = models.TextField()
    attached = models.FileField(upload_to='counsels/', blank=True)


class Approval(models.Model):
    counsel = models.OneToOneField(Counsel, on_delete=models.CASCADE)
    is_completed = models.BooleanField(default=False)
    is_approved = models.NullBooleanField(null=True)
    created = models.DateTimeField(auto_now_add=True)
    count = models.IntegerField()
    n1 = models.ForeignKey(User, related_name='n1')
    n2 = models.ForeignKey(User, related_name='n2', null=True)
    n3 = models.ForeignKey(User, related_name='n3', null=True)
    n4 = models.ForeignKey(User, related_name='n4', null=True)
    n5 = models.ForeignKey(User, related_name='n5', null=True)


class ApprovalUnit(models.Model):
    user = models.ForeignKey(User)
    approval = models.ForeignKey(Approval, on_delete=models.CASCADE)
    is_completed = models.BooleanField(default=False)
    is_approved = models.NullBooleanField(null=True)
    completed_date = models.DateTimeField(null=True)
    created = models.DateTimeField(auto_now_add=True)
#     comments = models.TextField(null=True)

    def __unicode__(self):
        return self.user.profile.name

core/views.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import login, logout, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import User
from django.db import transaction
from django.db.models import Q
from django.urls import reverse
from django.http import HttpResponseRedirect, Http404, JsonResponse, HttpResponse
from django.utils.translation import gettext as _
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

import datetime

from core.forms import (
    SignUpForm, ProfileForm, AnnouncementForm, SoldierForm, SoldierDetailForm,
    CounselForm
)
from core.models import (
    Profile, Announcement, Soldier, SoldierDetail, Sol_User_rel, Counsel,
    Approval, ApprovalUnit
)

# Create your views here.

# user

def index(request):
    if not request.user.is_authenticated:
        return redirect('login')
    soldier_list = Soldier.objects.filter(sol_user_rel__user=request.user).order_by('id')[:5]
    announcement_imp = Announcement.objects.filter(importance=True).order_by('-created')[:2]
    announcement_list = Announcement.objects.filter(importance=False).order_by('-created')[:3]
    return render(request, 'index.html', {
        'soldier_list':soldier_list,
        'announcement_imp': announcement_imp,
        'announcement_list': announcement_list,
    })

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            print form.data
            user = form.save()
            user.refresh_from_db()
            user.profile.name = form.cleaned_data.get('name')
            user.profile.department = form.cleaned_data.get('department')
            user.profile.position = form.cleaned_data.get('position')
            user.profile.phone_num = form.cleaned_data.get('phone_num')
            user.profile.rank = form.cleaned_data.get('rank')
            user.save()
            messages.success(request, '가입이 완료되었습니다. 로그인 해주십시오.')
            return redirect('login')
        else:
            messages.warning(request, '다시 작성해주십시오.')
    else:
        form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form})

def profile(request):
    return render(request, 'profile/profile.html', {})

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.info(request, '비밀번호가 성공적으로 변경되었습니다. 다시 로그인해 주십시오')
            logout(request)
            return redirect('login')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'profile/profile-change-password.html',
                  {'form': form})

@transaction.atomic
def update_profile(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST, instance=request.user.profile)
        if form.is_valid():
            form.save()
            messages.success(request, _('성공적으로 변경되었습니다.'))
            return redirect('home')
        else:
            messages.error(request, _('에러를 확인해 주십시오.'))

    else:
        form = ProfileForm(instance=request.user.profile)
    return render(request, 'profile/profile-update.html',{'form':form})


# announcement


def announcement_list(request):
    announcement_imp = Announcement.objects.filter(importance=True).order_by('-created')
    announcement_list = Announcement.objects.filter(importance=False).order_by('-created')

    q = request.GET.get("q")
    if q:
        announcement_list = announcement_list.filter(title__icontains=q)

    page = request.GET.get('page', 1)
    paginator = Paginator(announcement_list, 10)
    try:
        announcements = paginator.page(page)
    except PageNotAnInteger:
        announcements = paginator.page(1)
    except EmptyPage:
        announcements = paginator.page(paginator.num_pages)

    return render(request, 'announcement/list.html',
                  {'announcements':announcements,
                  'announcements_imp':announcement_imp})

def announcement_create(request):
    if request.method == 'POST':
        form = AnnouncementForm(request.POST, request.FILES)
        if form.is_valid():
            announcement = form.save(commit=False)
            announcement.user = request.user
            announcement.save()
            messages.success(request, '공지사항 등록이 완료되었습니다.')
            return redirect(reverse('announcement-detail',
                                    kwargs={'pk':announcement.id}))
    else:
        form = AnnouncementForm()
    return render(request, 'announcement/create.html',{'form':form})

def announcement_detail(request, pk):
    announcement = Announcement.objects.get(pk=pk)
    auth = False;
    if request.user == announcement.user:
        auth = True;
    return render(request, 'announcement/detail.html',
                  {'announcement':announcement, 'auth':auth})

def announcement_update(request, pk):
    announcement = Announcement.objects.get(pk=pk)
    if request.method == 'POST':
        form = AnnouncementForm(request.POST, request.FILES, instance=announcement)
        if form.is_valid():
            form.save()
            messages.info(request, '공지사항 수정이 완료되었습니다.')
            return redirect(reverse('announcement-detail',
                                    kwargs={'pk':announcement.id}))
    else:
        form = AnnouncementForm(instance=announcement)
    return render(request, 'announcement/create.html',{'form':form})

def announcement_delete(request, pk):
    if request.method == 'POST':
        announcement = Announcement.objects.get(pk=pk)
        announcement.delete()
        messages.info(request, '공지사항 삭제가 완료되었습니다.')
        return redirect('announcement-list')


# soldier

def soldier_list(request):
    soldiers = Soldier.objects.filter(sol_user_rel__user=request.user).all()
    return render(request, 'soldier/list.html', {'soldiers':soldiers})

def soldier_detail(request, pk):
    soldier = Soldier.objects.get(pk=pk)
    auth = False
    if soldier.superuser == request.user:
        auth = True
    detail = SoldierDetail.objects.get(soldier=soldier)
    return render(request, 'soldier/detail.html', {
        'soldier': soldier,
        'detail': detail,
        'auth': auth
    })

def soldier_enroll_user(request, pk):
    soldier = Soldier.objects.get(pk=pk)

    if soldier.superuser != request.user:
        return Http404

    if request.method == 'POST' :
        user_id = request.POST['userid']
        Sol_User_rel.objects.get_or_create(soldier=soldier, user_id=user_id)

    users = User.objects.filter(~Q(sol_user_rel__soldier=soldier))
    cur_users = User.objects.filter(sol_user_rel__soldier=soldier)

    return render(request, 'soldier/enroll.html', {
        'cur_users': cur_users, 'users': users, 'pk': pk})

def ajax_soldier(request, pk):
    name = request.GET.get('name', None)
    users = User.objects.filter(profile__name__icontains=name)

    return render(request, 'soldier/ajaxtable.html', {'users':users, 'pk':pk})


def soldier_create(request):
    if request.method == 'POST':
        form_1 = SoldierForm(request.POST, request.FILES)
        form_2 = SoldierDetailForm(request.POST)
        if form_1.is_valid() and form_2.is_valid():
            soldier = form_1.save(commit=False)
            soldier.superuser = request.user
            soldier.save()
            detail = form_2.save(commit=False)
            detail.soldier = soldier
            detail.save()
            Sol_User_rel.objects.create(soldier=soldier,user=request.user)
            messages.success(request, '병사 등록이 완료되었습니다.')
            return redirect(reverse('soldier-detail',
                                   kwargs={'pk': soldier.id}))
    else:
        form_1 = SoldierForm()
        form_2 = SoldierDetailForm()

    return render(request, 'soldier/create.html', {
            'soldierForm': form_1,
            'detailForm': form_2,
        })

def soldier_update(request, pk):
    soldier = Soldier.objects.get(pk=pk)
    soldier_detail = SoldierDetail.objects.get(soldier=soldier)
    if request.method == 'POST':
        form_1 = SoldierForm(request.POST, request.FILES, instance=soldier)
        form_2 = SoldierDetailForm(request.POST, instance=soldier_detail)
        if form_1.is_valid() and form_2.is_valid():
            form_1.save()
            form_2.save()
            messages.info(request, '병사 수정이 완료되었습니다.')
            return redirect(reverse('soldier-detail',
                                 kwargs={'pk':soldier.id}))
    else:
        form_1 = SoldierForm(instance=soldier)
        form_2 = SoldierDetailForm(instance=soldier_detail)

    return render(request, 'soldier/update.html', {
            'soldierForm': form_1,
            'detailForm': form_2
        })

# counsel

def counsel(request):
    soldier_list = Soldier.objects.filter(sol_user_rel__user=request.user).all()
    return render(request, 'counsel/index.html',{
        'soldiers': soldier_list,
    })

def counsel_list(request, pk):
    counsel_list = Counsel.objects.filter(soldier=pk,approval__is_approved=True).order_by('-date')
    page = request.GET.get('page', 1)

    paginator = Paginator(counsel_list, 10)
    try:
        counsels = paginator.page(page)
    except PageNotAnInteger:
        counsels = paginator.page(1)
    except EmptyPage:
        counsels = paginator.page(paginator.num_pages)

    return render(request,'counsel/list.html', {
        'counsels': counsel_list,
        'pk': pk
    })

def counsel_create(request, pk):
    soldier = Soldier.objects.get(pk=pk)
    if request.method == 'POST':
        form = CounselForm(request.POST, request.FILES)
        if form.is_valid():
            counsel = form.save(commit=False)

core/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="utf-8">
    <title>My project</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/earlyaccess/jejugothic.css" rel="stylesheet" />
    <style>
        body {font-family: 'Jeju Gothic', sans-serif;
        }
    </style>

    <!-- scripts loaded here -->
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

  </head>
  <body>
    <!-- navbar -->
      <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'home' %}">Brand</a>
            </div>

            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <li><p class="navbar-text">
                            {{ request.user.profile.get_rank_display }} {{ request.user.profile.name }}님, 환영합니다.
                            </p></li>
                        <li><a href="{% url 'profile' %}">정보수정</a></li>
                        <li><a href="{% url 'logout' %}">로그아웃</a></li>
                    {% else %}
                        <li><a href="{% url 'login' %}">로그인</a></li>
                        <li><a href="{% url 'signup' %}">회원가입</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
      </nav>

      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}" style = "height:35px;padding-top:8px;width:80%;Float:left;margin-left:10%;">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
               <span class="glyphicon glyphicon-ok"></span>

                    {{ message }}
          </div>
        {% endfor %}
    {% endif %}

	{% if user.is_authenticated %}
    <div class="container">
        <div class="page-header" id="banner">

   			<!-- left-sidebar -->
            <div class="row">
                <div role="tabpanel">
                    <div class="col-sm-3">
                		<ul class="nav nav-pills brand-pills nav-stacked" role="tablist">
                            <li class="brand-nav"><a href="{% url 'soldier-list' %}">병사관리</a></li>
                            <li class="brand-nav"><a href="{% url 'counsel' %}">면담관리</a></li>
                            <li class="brand-nav"><a href="{% url 'approval' %}">결재관리 {{ approval_count }}</a></li>
                            <li class="brand-nav"><a href="{% url 'announcement-list' %}">공지사항</a></li>
                        </ul>
                    </div>
                    <div class="col-sm-7">
                		<div class="tab-content">
                    		<div>
                        		{% block content %}
                                {% endblock %}
                    		</div>
                		</div>
            		</div>
        		</div>
    		</div>
        </div>
        {% endif %}

        <footer class="container-fluid">
            <p class="text-right small">©2016-2017 Company</p>
        </footer>
      </div>

<script>
    function openStatus(url){
        window.open(url,"test","width=750,height=230");
    }
</script>
  </body>
</html>

core/templates/index.html
{% extends 'base.html' %}

{% block content %}

<style>
    #top {
        height: 200px;
    }
    #left, #right {
        width:48%;
        height: 200px;
    }
    #left { float: left; }
    #right { float: right; }
</style>

<h2 class="hidden-xs-down">도움·배려병사 관리체계에 오신 것을 환영합니다!</h2>
<hr style="margin:10px">
<div id="top" class="panel panel-default">
    <div class="panel-heading" style="height:40px">
        <h3 class="panel-title" style="float:left">병사현황</h3>
        <a href="{% url 'approval_req_list' %}" style="float:right">
            <small>+more</small>
        </a>
    </div>
    <div class="panel-body">
        <ul>
            {% for soldier in soldier_list %}
            <li><a href="{% url 'soldier-detail' soldier.id %}">
                {{ soldier.name }}</a></li>
            {% endfor %}
        </ul>
    </div>
</div>
<div id="left" class="panel panel-default">
    <div class="panel-heading" style="height:40px">
        <h3 class="panel-title" style="float:left">결재대기목록</h3>
        <a href="{% url 'approval_proceed_list' %}" style="float:right">
            <small>+more</small>
        </a>
    </div>
    <div class="panel-body">
        <ul>
            {% for item in completed %}
            <li><a href="javascript:openDetail('{% url 'approval-detail-non-approve' item.id %}');">
                {{ item.counsel.soldier.name }} {{item.created }}</a></li>
            {% endfor %}
        </ul>
    </div>
</div>
<div id="right" class="panel panel-default">
    <div class="panel-heading" style="height:40px">
        <h3 class="panel-title" style="float:left">공지사항</h3>
        <a href="{% url 'approval_completed_list' %}" style="float:right">
            <small>+more</small>
        </a>
    </div>
    <div class="panel-body">
        <ul>
            {% for announcement in announcement_imp %}
            <li><a href="'{% url 'announcement-detail' announcement.id %}">
                <strong>{{ announcement.title }} {{item.created }}</strong></a></li>
            {% endfor %}
            {% for announcement in announcement_list %}
            <li><a href="'{% url 'announcement-detail' announcement.id %}">
                {{ announcement.title }} {{item.created }}</a></li>
            {% endfor %}
        </ul>
    </div>
</div>

{% endblock %}